version: '3.7'

networks:
  ethereum_net:

services:
  geth:
    image: ethereum/client-go
    restart: always
    networks:
      - ethereum_net
    volumes:
      - ./geth-data:/data
      - /src:/src
    command:
      --datadir /data --sepolia --syncmode snap --cache=2048 --http --http.port 3334 --http.addr=0.0.0.0 --http.api eth,net,web3 --ws --ws.port 3344 --ws.api eth,net,web3
    ports:
      - "3334:3334"
      - "3344:3344"
      - "8551:8551"
      - 30303:30303/tcp
      - 30303:30303/udp

  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain
    restart: always
    networks:
      - ethereum_net
    volumes:
      - ./prysm-data:/data
      - /src:/src
    ports:
      - "4000:4000"
      - "3500:3500"
      - 13000:13000/tcp
      - 12000:12000/udp
    command:
      --sepolia --accept-terms-of-use --checkpoint-sync-url=https://sepolia.beaconstate.info --rpc-host=0.0.0.0  --block-batch-limit 512 --grpc-gateway-host=0.0.0.0 
    depends_on:
      - geth
