version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

networks:
    ethereum:

services:
    geth:
        image: ethereum/client-go:stable
        restart: always
        hostname: geth
        networks:
            - ethereum
        volumes:
            - ./data/geth-data:/data
            - ./data/ethereum:/ethereum
        command: --sepolia --cache=2048 --authrpc.jwtsecret=/ethereum/jwt.hex --syncmode snap --http --http.port=8545 --http.api=eth,net,web3,debug,admin,txpool --http.corsdomain="*" --http.vhosts="*" --http.addr=0.0.0.0 --ws --ws.port=8546 --ws.api=eth,net,web3,admin,txpool --ws.origins="*"  --ws.addr=0.0.0.0 --authrpc.port=8551 --authrpc.vhosts="*" --authrpc.addr=0.0.0.0
        ports:
            - ${BEACON_API_IP}:8545:8545
            - ${BEACON_API_IP}:8546:8546
            - ${BEACON_API_IP}:8551:8551
            - ${BEACON_API_IP}:6060:6060
            - ${BEACON_API_IP}:8086:8086
            - 30303:30303/tcp
            - 30303:30303/udp
        <<: *logging

    beacon:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:${BEACON_VERSION}
        restart: always
        hostname: beacon
        depends_on:
            - geth
        networks:
            - ethereum
        volumes:
            - ./data/prysm-data:/data
            - ./data/ethereum:/ethereum
            - ./configs:/configs
        ports:
            - ${BEACON_API_IP}:4000:4000
            - ${BEACON_API_IP}:3500:3500
            - 13000:13000
            - 12000:12000
        command: --config-file=/configs/beacon.yaml
        <<: *logging

