sepolia: true

datadir: /data

accept-terms-of-use: true

jwt-secret: /ethereum/jwt.hex

execution-endpoint: http://geth:8551

checkpoint-sync-url: https://sepolia.beaconstate.info
genesis-beacon-api-url: https://sepolia.beaconstate.info

block-batch-limit: 128

rpc-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
#EOF
