sepolia: true
datadir: /data

accept-terms-of-use: true

jwt-secret: /ethereum/jwt.hex

execution-endpoint: http://geth:8551

checkpoint-sync-url: https://sepolia.beaconstate.info
genesis-beacon-api-url: https://sepolia.beaconstate.info

block-batch-limit: 128

#######################
# Connectivity settings
p2p-host-ip: ""
p2p-host-dns: ""

rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0

grpc-gateway-host: 0.0.0.0
grpc-gateway-port: 3500
eth-api-port: 3501

p2p-tcp-port: 13000

p2p-max-peers: 100
